language: php
php:
  - 5.5
  - 5.4
  - 5.3
  - 5.2

env:
  - CC=clang   CFLAGS=""
  - CC=clang   CFLAGS="-g -O0"
  - CC=gcc-4.6 CFLAGS=""
  - CC=gcc-4.6 CFLAGS="-g -O0"

before_script:
  - sudo apt-get install $CC
  - $CC --version

script:
  - phpize
  - ./configure --enable-igbinary
  - make
  - NO_INTERACTION=1 make test
